# Generated by Django 3.0.5 on 2020-05-16 21:14

from django.db import migrations, models
import django.db.models.deletion
import projects.projecttype
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('custom_heading', models.CharField(help_text='Overwrites the default title', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('type_of_project', projects.projecttype.TypesOfProjectsField(choices=[('Complete', 'Complete Project'), ('Current', 'Current Project')], max_length=10, null=True)),
                ('project_description', wagtail.core.fields.RichTextField(null=True)),
                ('principal_investigator', wagtail.core.fields.RichTextField(null=True)),
                ('team', wagtail.core.fields.RichTextField(null=True)),
                ('intended_outcomes', wagtail.core.fields.RichTextField(null=True)),
                ('project_documents', wagtail.core.fields.RichTextField(null=True)),
                ('project_outputs', wagtail.core.fields.RichTextField(null=True)),
                ('project_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
