# Generated by Django 3.0.5 on 2020-06-06 19:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.StreamField([('table', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(required=True)), ('points', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('SNo', wagtail.core.blocks.IntegerBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(max_length=500, required=True)), ('venue', wagtail.core.blocks.CharBlock(max_length=1000, required=True)), ('dates', wagtail.core.blocks.CharBlock(max_length=300, required=True)), ('attendees', wagtail.core.blocks.CharBlock(max_length=400, required=True)), ('host', wagtail.core.blocks.CharBlock(max_length=300, required=True))])))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Outreach Page',
                'verbose_name_plural': 'Outreach Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
