# Generated by Django 3.0.5 on 2020-06-06 19:49

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachpage',
            name='content',
            field=wagtail.core.fields.StreamField([('table', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(required=True)), ('points', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('SNo', wagtail.core.blocks.IntegerBlock(required=True)), ('title', wagtail.core.blocks.RichTextBlock(icon='text')), ('venue', wagtail.core.blocks.RichTextBlock(icon='text')), ('dates', wagtail.core.blocks.CharBlock(max_length=300, required=True)), ('attendees', wagtail.core.blocks.CharBlock(max_length=400, required=True)), ('host', wagtail.core.blocks.CharBlock(max_length=300, required=True))])))]))], blank=True, null=True),
        ),
    ]
