# Generated by Django 3.0.5 on 2020-06-08 15:19

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='supervisors',
            field=wagtail.core.fields.StreamField([('supervisors', wagtail.core.blocks.StructBlock([('info', wagtail.core.blocks.RichTextBlock(icon='text')), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('name', wagtail.core.blocks.RichTextBlock(icon='text')), ('Dept', wagtail.core.blocks.RichTextBlock(icon='text')), ('contact', wagtail.core.blocks.RichTextBlock(icon='text')), ('website', wagtail.core.blocks.URLBlock(required=True))])))]))], blank=True, null=True),
        ),
    ]
