# Generated by Django 3.0.5 on 2020-05-11 19:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('services_offered', wagtail.core.fields.StreamField([('services', wagtail.core.blocks.StructBlock([('point', wagtail.core.blocks.CharBlock(help_text='Add a new service point', required=True)), ('info', wagtail.core.blocks.RichTextBlock(icon='text'))]))], blank=True, null=True)),
                ('ircc', wagtail.core.fields.RichTextField(null=True)),
                ('team', wagtail.core.fields.RichTextField(null=True)),
                ('areas_and_projects', wagtail.core.fields.RichTextField(null=True)),
            ],
            options={
                'verbose_name': 'Services Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
