# Generated by Django 3.0.5 on 2020-04-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200429_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='what_is_tdsc',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
