# Generated by Django 3.0.5 on 2020-05-07 19:30

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='background',
            field=wagtail.core.fields.StreamField([('background', wagtail.core.blocks.StructBlock([('text1', wagtail.core.blocks.RichTextBlock(icon='text')), ('text2', wagtail.core.blocks.RichTextBlock(icon='text'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='proposal',
            field=wagtail.core.fields.StreamField([('proposal', streams.blocks.RichtextProposalBlock())], blank=True, null=True),
        ),
    ]
